version: "3.1"

services:
  gate:
    image: akaletr/gate:latest
    environment:
      ENV: "dev"
      PORT: ":8080"
      DATABASE_DSN: "host=62.109.5.203 user=akaletr password=adelaida2011 dbname=gate port=5432"
      AUTH_DSN: "host=62.109.5.203 user=akaletr password=adelaida2011 dbname=auth port=5432"
      METRIC_DSN: "host=62.109.5.203 user=akaletr password=adelaida2011 dbname=auth port=5432"
    ports:
      - "3021:8080"