// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAggYmDataUtmMedium = "agg_ym_data_utm_medium"

// AggYmDataUtmMedium mapped from table <agg_ym_data_utm_medium>
type AggYmDataUtmMedium struct {
	Timestamp time.Time `gorm:"column:timestamp;primaryKey" json:"timestamp"`
	UtmMedium string    `gorm:"column:utm_medium;primaryKey" json:"utm_medium"`
	Pageviews int32     `gorm:"column:pageviews" json:"pageviews"`
	Users     int32     `gorm:"column:users" json:"users"`
}

// TableName AggYmDataUtmMedium's table name
func (*AggYmDataUtmMedium) TableName() string {
	return TableNameAggYmDataUtmMedium
}
