// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDimensionReference = "dimension_reference"

// DimensionReference mapped from table <dimension_reference>
type DimensionReference struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name" json:"name"`
	Value string `gorm:"column:value" json:"value"`
}

// TableName DimensionReference's table name
func (*DimensionReference) TableName() string {
	return TableNameDimensionReference
}
