// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	DimensionReference *dimensionReference
	YmData20240101     *ymData20240101
	YmData20240102     *ymData20240102
	YmData20240103     *ymData20240103
	YmData20240104     *ymData20240104
	YmData20240105     *ymData20240105
	YmData20240106     *ymData20240106
	YmData20240107     *ymData20240107
	YmData20240108     *ymData20240108
	YmData20240109     *ymData20240109
	YmData20240110     *ymData20240110
	YmData20240111     *ymData20240111
	YmData20240112     *ymData20240112
	YmData20240113     *ymData20240113
	YmData20240114     *ymData20240114
	YmData20240115     *ymData20240115
	YmData20240116     *ymData20240116
	YmData20240117     *ymData20240117
	YmData20240118     *ymData20240118
	YmData20240119     *ymData20240119
	YmData20240120     *ymData20240120
	YmData20240121     *ymData20240121
	YmData20240122     *ymData20240122
	YmData20240123     *ymData20240123
	YmData20240124     *ymData20240124
	YmData20240125     *ymData20240125
	YmData20240126     *ymData20240126
	YmData20240127     *ymData20240127
	YmData20240128     *ymData20240128
	YmData20240129     *ymData20240129
	YmData20240130     *ymData20240130
	YmData20240131     *ymData20240131
	YmData20240201     *ymData20240201
	YmData20240202     *ymData20240202
	YmData20240203     *ymData20240203
	YmData20240204     *ymData20240204
	YmData20240205     *ymData20240205
	YmData20240206     *ymData20240206
	YmData20240207     *ymData20240207
	YmData20240208     *ymData20240208
	YmData20240209     *ymData20240209
	YmData20240210     *ymData20240210
	YmData20240211     *ymData20240211
	YmData20240212     *ymData20240212
	YmData20240213     *ymData20240213
	YmData20240214     *ymData20240214
	YmData20240215     *ymData20240215
	YmData20240216     *ymData20240216
	YmData20240217     *ymData20240217
	YmData20240218     *ymData20240218
	YmData20240219     *ymData20240219
	YmData20240220     *ymData20240220
	YmData20240221     *ymData20240221
	YmData20240222     *ymData20240222
	YmData20240223     *ymData20240223
	YmData20240224     *ymData20240224
	YmData20240225     *ymData20240225
	YmData20240226     *ymData20240226
	YmData20240227     *ymData20240227
	YmData20240228     *ymData20240228
	YmData20240229     *ymData20240229
	YmData20240301     *ymData20240301
	YmData20240302     *ymData20240302
	YmData20240303     *ymData20240303
	YmData20240304     *ymData20240304
	YmData20240305     *ymData20240305
	YmData20240306     *ymData20240306
	YmData20240307     *ymData20240307
	YmData20240308     *ymData20240308
	YmData20240309     *ymData20240309
	YmData20240310     *ymData20240310
	YmData20240311     *ymData20240311
	YmData20240312     *ymData20240312
	YmData20240313     *ymData20240313
	YmData20240314     *ymData20240314
	YmData20240315     *ymData20240315
	YmData20240316     *ymData20240316
	YmData20240317     *ymData20240317
	YmData20240318     *ymData20240318
	YmData20240319     *ymData20240319
	YmData20240320     *ymData20240320
	YmData20240321     *ymData20240321
	YmData20240322     *ymData20240322
	YmData20240323     *ymData20240323
	YmData20240324     *ymData20240324
	YmData20240325     *ymData20240325
	YmData20240326     *ymData20240326
	YmData20240327     *ymData20240327
	YmData20240328     *ymData20240328
	YmData20240329     *ymData20240329
	YmData20240330     *ymData20240330
	YmData20240331     *ymData20240331
	YmData20240401     *ymData20240401
	YmData20240402     *ymData20240402
	YmData20240403     *ymData20240403
	YmData20240404     *ymData20240404
	YmData20240405     *ymData20240405
	YmData20240406     *ymData20240406
	YmData20240407     *ymData20240407
	YmData20240408     *ymData20240408
	YmData20240409     *ymData20240409
	YmData20240410     *ymData20240410
	YmData20240411     *ymData20240411
	YmData20240412     *ymData20240412
	YmData20240413     *ymData20240413
	YmData20240414     *ymData20240414
	YmData20240415     *ymData20240415
	YmData20240416     *ymData20240416
	YmData20240417     *ymData20240417
	YmData20240418     *ymData20240418
	YmData20240419     *ymData20240419
	YmData20240420     *ymData20240420
	YmData20240421     *ymData20240421
	YmData20240422     *ymData20240422
	YmData20240423     *ymData20240423
	YmData20240424     *ymData20240424
	YmData20240425     *ymData20240425
	YmData20240426     *ymData20240426
	YmData20240427     *ymData20240427
	YmData20240428     *ymData20240428
	YmData20240429     *ymData20240429
	YmData20240430     *ymData20240430
	YmData20240501     *ymData20240501
	YmData20240502     *ymData20240502
	YmData20240503     *ymData20240503
	YmData20240504     *ymData20240504
	YmData20240505     *ymData20240505
	YmData20240506     *ymData20240506
	YmData20240507     *ymData20240507
	YmData20240508     *ymData20240508
	YmData20240509     *ymData20240509
	YmData20240510     *ymData20240510
	YmData20240511     *ymData20240511
	YmData20240512     *ymData20240512
	YmData20240513     *ymData20240513
	YmData20240514     *ymData20240514
	YmData20240515     *ymData20240515
	YmData20240516     *ymData20240516
	YmData20240517     *ymData20240517
	YmData20240518     *ymData20240518
	YmData20240519     *ymData20240519
	YmData20240520     *ymData20240520
	YmData20240521     *ymData20240521
	YmData20240522     *ymData20240522
	YmData20240523     *ymData20240523
	YmData20240524     *ymData20240524
	YmData20240525     *ymData20240525
	YmData20240526     *ymData20240526
	YmData20240527     *ymData20240527
	YmData20240528     *ymData20240528
	YmData20240529     *ymData20240529
	YmData20240530     *ymData20240530
	YmData20240531     *ymData20240531
	YmData20240601     *ymData20240601
	YmData20240602     *ymData20240602
	YmData20240603     *ymData20240603
	YmData20240604     *ymData20240604
	YmData20240605     *ymData20240605
	YmData20240606     *ymData20240606
	YmData20240607     *ymData20240607
	YmData20240608     *ymData20240608
	YmData20240609     *ymData20240609
	YmData20240610     *ymData20240610
	YmData20240611     *ymData20240611
	YmData20240612     *ymData20240612
	YmData20240613     *ymData20240613
	YmData20240614     *ymData20240614
	YmData20240615     *ymData20240615
	YmData20240616     *ymData20240616
	YmData20240617     *ymData20240617
	YmData20240618     *ymData20240618
	YmDatum            *ymDatum
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	DimensionReference = &Q.DimensionReference
	YmData20240101 = &Q.YmData20240101
	YmData20240102 = &Q.YmData20240102
	YmData20240103 = &Q.YmData20240103
	YmData20240104 = &Q.YmData20240104
	YmData20240105 = &Q.YmData20240105
	YmData20240106 = &Q.YmData20240106
	YmData20240107 = &Q.YmData20240107
	YmData20240108 = &Q.YmData20240108
	YmData20240109 = &Q.YmData20240109
	YmData20240110 = &Q.YmData20240110
	YmData20240111 = &Q.YmData20240111
	YmData20240112 = &Q.YmData20240112
	YmData20240113 = &Q.YmData20240113
	YmData20240114 = &Q.YmData20240114
	YmData20240115 = &Q.YmData20240115
	YmData20240116 = &Q.YmData20240116
	YmData20240117 = &Q.YmData20240117
	YmData20240118 = &Q.YmData20240118
	YmData20240119 = &Q.YmData20240119
	YmData20240120 = &Q.YmData20240120
	YmData20240121 = &Q.YmData20240121
	YmData20240122 = &Q.YmData20240122
	YmData20240123 = &Q.YmData20240123
	YmData20240124 = &Q.YmData20240124
	YmData20240125 = &Q.YmData20240125
	YmData20240126 = &Q.YmData20240126
	YmData20240127 = &Q.YmData20240127
	YmData20240128 = &Q.YmData20240128
	YmData20240129 = &Q.YmData20240129
	YmData20240130 = &Q.YmData20240130
	YmData20240131 = &Q.YmData20240131
	YmData20240201 = &Q.YmData20240201
	YmData20240202 = &Q.YmData20240202
	YmData20240203 = &Q.YmData20240203
	YmData20240204 = &Q.YmData20240204
	YmData20240205 = &Q.YmData20240205
	YmData20240206 = &Q.YmData20240206
	YmData20240207 = &Q.YmData20240207
	YmData20240208 = &Q.YmData20240208
	YmData20240209 = &Q.YmData20240209
	YmData20240210 = &Q.YmData20240210
	YmData20240211 = &Q.YmData20240211
	YmData20240212 = &Q.YmData20240212
	YmData20240213 = &Q.YmData20240213
	YmData20240214 = &Q.YmData20240214
	YmData20240215 = &Q.YmData20240215
	YmData20240216 = &Q.YmData20240216
	YmData20240217 = &Q.YmData20240217
	YmData20240218 = &Q.YmData20240218
	YmData20240219 = &Q.YmData20240219
	YmData20240220 = &Q.YmData20240220
	YmData20240221 = &Q.YmData20240221
	YmData20240222 = &Q.YmData20240222
	YmData20240223 = &Q.YmData20240223
	YmData20240224 = &Q.YmData20240224
	YmData20240225 = &Q.YmData20240225
	YmData20240226 = &Q.YmData20240226
	YmData20240227 = &Q.YmData20240227
	YmData20240228 = &Q.YmData20240228
	YmData20240229 = &Q.YmData20240229
	YmData20240301 = &Q.YmData20240301
	YmData20240302 = &Q.YmData20240302
	YmData20240303 = &Q.YmData20240303
	YmData20240304 = &Q.YmData20240304
	YmData20240305 = &Q.YmData20240305
	YmData20240306 = &Q.YmData20240306
	YmData20240307 = &Q.YmData20240307
	YmData20240308 = &Q.YmData20240308
	YmData20240309 = &Q.YmData20240309
	YmData20240310 = &Q.YmData20240310
	YmData20240311 = &Q.YmData20240311
	YmData20240312 = &Q.YmData20240312
	YmData20240313 = &Q.YmData20240313
	YmData20240314 = &Q.YmData20240314
	YmData20240315 = &Q.YmData20240315
	YmData20240316 = &Q.YmData20240316
	YmData20240317 = &Q.YmData20240317
	YmData20240318 = &Q.YmData20240318
	YmData20240319 = &Q.YmData20240319
	YmData20240320 = &Q.YmData20240320
	YmData20240321 = &Q.YmData20240321
	YmData20240322 = &Q.YmData20240322
	YmData20240323 = &Q.YmData20240323
	YmData20240324 = &Q.YmData20240324
	YmData20240325 = &Q.YmData20240325
	YmData20240326 = &Q.YmData20240326
	YmData20240327 = &Q.YmData20240327
	YmData20240328 = &Q.YmData20240328
	YmData20240329 = &Q.YmData20240329
	YmData20240330 = &Q.YmData20240330
	YmData20240331 = &Q.YmData20240331
	YmData20240401 = &Q.YmData20240401
	YmData20240402 = &Q.YmData20240402
	YmData20240403 = &Q.YmData20240403
	YmData20240404 = &Q.YmData20240404
	YmData20240405 = &Q.YmData20240405
	YmData20240406 = &Q.YmData20240406
	YmData20240407 = &Q.YmData20240407
	YmData20240408 = &Q.YmData20240408
	YmData20240409 = &Q.YmData20240409
	YmData20240410 = &Q.YmData20240410
	YmData20240411 = &Q.YmData20240411
	YmData20240412 = &Q.YmData20240412
	YmData20240413 = &Q.YmData20240413
	YmData20240414 = &Q.YmData20240414
	YmData20240415 = &Q.YmData20240415
	YmData20240416 = &Q.YmData20240416
	YmData20240417 = &Q.YmData20240417
	YmData20240418 = &Q.YmData20240418
	YmData20240419 = &Q.YmData20240419
	YmData20240420 = &Q.YmData20240420
	YmData20240421 = &Q.YmData20240421
	YmData20240422 = &Q.YmData20240422
	YmData20240423 = &Q.YmData20240423
	YmData20240424 = &Q.YmData20240424
	YmData20240425 = &Q.YmData20240425
	YmData20240426 = &Q.YmData20240426
	YmData20240427 = &Q.YmData20240427
	YmData20240428 = &Q.YmData20240428
	YmData20240429 = &Q.YmData20240429
	YmData20240430 = &Q.YmData20240430
	YmData20240501 = &Q.YmData20240501
	YmData20240502 = &Q.YmData20240502
	YmData20240503 = &Q.YmData20240503
	YmData20240504 = &Q.YmData20240504
	YmData20240505 = &Q.YmData20240505
	YmData20240506 = &Q.YmData20240506
	YmData20240507 = &Q.YmData20240507
	YmData20240508 = &Q.YmData20240508
	YmData20240509 = &Q.YmData20240509
	YmData20240510 = &Q.YmData20240510
	YmData20240511 = &Q.YmData20240511
	YmData20240512 = &Q.YmData20240512
	YmData20240513 = &Q.YmData20240513
	YmData20240514 = &Q.YmData20240514
	YmData20240515 = &Q.YmData20240515
	YmData20240516 = &Q.YmData20240516
	YmData20240517 = &Q.YmData20240517
	YmData20240518 = &Q.YmData20240518
	YmData20240519 = &Q.YmData20240519
	YmData20240520 = &Q.YmData20240520
	YmData20240521 = &Q.YmData20240521
	YmData20240522 = &Q.YmData20240522
	YmData20240523 = &Q.YmData20240523
	YmData20240524 = &Q.YmData20240524
	YmData20240525 = &Q.YmData20240525
	YmData20240526 = &Q.YmData20240526
	YmData20240527 = &Q.YmData20240527
	YmData20240528 = &Q.YmData20240528
	YmData20240529 = &Q.YmData20240529
	YmData20240530 = &Q.YmData20240530
	YmData20240531 = &Q.YmData20240531
	YmData20240601 = &Q.YmData20240601
	YmData20240602 = &Q.YmData20240602
	YmData20240603 = &Q.YmData20240603
	YmData20240604 = &Q.YmData20240604
	YmData20240605 = &Q.YmData20240605
	YmData20240606 = &Q.YmData20240606
	YmData20240607 = &Q.YmData20240607
	YmData20240608 = &Q.YmData20240608
	YmData20240609 = &Q.YmData20240609
	YmData20240610 = &Q.YmData20240610
	YmData20240611 = &Q.YmData20240611
	YmData20240612 = &Q.YmData20240612
	YmData20240613 = &Q.YmData20240613
	YmData20240614 = &Q.YmData20240614
	YmData20240615 = &Q.YmData20240615
	YmData20240616 = &Q.YmData20240616
	YmData20240617 = &Q.YmData20240617
	YmData20240618 = &Q.YmData20240618
	YmDatum = &Q.YmDatum
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		DimensionReference: newDimensionReference(db, opts...),
		YmData20240101:     newYmData20240101(db, opts...),
		YmData20240102:     newYmData20240102(db, opts...),
		YmData20240103:     newYmData20240103(db, opts...),
		YmData20240104:     newYmData20240104(db, opts...),
		YmData20240105:     newYmData20240105(db, opts...),
		YmData20240106:     newYmData20240106(db, opts...),
		YmData20240107:     newYmData20240107(db, opts...),
		YmData20240108:     newYmData20240108(db, opts...),
		YmData20240109:     newYmData20240109(db, opts...),
		YmData20240110:     newYmData20240110(db, opts...),
		YmData20240111:     newYmData20240111(db, opts...),
		YmData20240112:     newYmData20240112(db, opts...),
		YmData20240113:     newYmData20240113(db, opts...),
		YmData20240114:     newYmData20240114(db, opts...),
		YmData20240115:     newYmData20240115(db, opts...),
		YmData20240116:     newYmData20240116(db, opts...),
		YmData20240117:     newYmData20240117(db, opts...),
		YmData20240118:     newYmData20240118(db, opts...),
		YmData20240119:     newYmData20240119(db, opts...),
		YmData20240120:     newYmData20240120(db, opts...),
		YmData20240121:     newYmData20240121(db, opts...),
		YmData20240122:     newYmData20240122(db, opts...),
		YmData20240123:     newYmData20240123(db, opts...),
		YmData20240124:     newYmData20240124(db, opts...),
		YmData20240125:     newYmData20240125(db, opts...),
		YmData20240126:     newYmData20240126(db, opts...),
		YmData20240127:     newYmData20240127(db, opts...),
		YmData20240128:     newYmData20240128(db, opts...),
		YmData20240129:     newYmData20240129(db, opts...),
		YmData20240130:     newYmData20240130(db, opts...),
		YmData20240131:     newYmData20240131(db, opts...),
		YmData20240201:     newYmData20240201(db, opts...),
		YmData20240202:     newYmData20240202(db, opts...),
		YmData20240203:     newYmData20240203(db, opts...),
		YmData20240204:     newYmData20240204(db, opts...),
		YmData20240205:     newYmData20240205(db, opts...),
		YmData20240206:     newYmData20240206(db, opts...),
		YmData20240207:     newYmData20240207(db, opts...),
		YmData20240208:     newYmData20240208(db, opts...),
		YmData20240209:     newYmData20240209(db, opts...),
		YmData20240210:     newYmData20240210(db, opts...),
		YmData20240211:     newYmData20240211(db, opts...),
		YmData20240212:     newYmData20240212(db, opts...),
		YmData20240213:     newYmData20240213(db, opts...),
		YmData20240214:     newYmData20240214(db, opts...),
		YmData20240215:     newYmData20240215(db, opts...),
		YmData20240216:     newYmData20240216(db, opts...),
		YmData20240217:     newYmData20240217(db, opts...),
		YmData20240218:     newYmData20240218(db, opts...),
		YmData20240219:     newYmData20240219(db, opts...),
		YmData20240220:     newYmData20240220(db, opts...),
		YmData20240221:     newYmData20240221(db, opts...),
		YmData20240222:     newYmData20240222(db, opts...),
		YmData20240223:     newYmData20240223(db, opts...),
		YmData20240224:     newYmData20240224(db, opts...),
		YmData20240225:     newYmData20240225(db, opts...),
		YmData20240226:     newYmData20240226(db, opts...),
		YmData20240227:     newYmData20240227(db, opts...),
		YmData20240228:     newYmData20240228(db, opts...),
		YmData20240229:     newYmData20240229(db, opts...),
		YmData20240301:     newYmData20240301(db, opts...),
		YmData20240302:     newYmData20240302(db, opts...),
		YmData20240303:     newYmData20240303(db, opts...),
		YmData20240304:     newYmData20240304(db, opts...),
		YmData20240305:     newYmData20240305(db, opts...),
		YmData20240306:     newYmData20240306(db, opts...),
		YmData20240307:     newYmData20240307(db, opts...),
		YmData20240308:     newYmData20240308(db, opts...),
		YmData20240309:     newYmData20240309(db, opts...),
		YmData20240310:     newYmData20240310(db, opts...),
		YmData20240311:     newYmData20240311(db, opts...),
		YmData20240312:     newYmData20240312(db, opts...),
		YmData20240313:     newYmData20240313(db, opts...),
		YmData20240314:     newYmData20240314(db, opts...),
		YmData20240315:     newYmData20240315(db, opts...),
		YmData20240316:     newYmData20240316(db, opts...),
		YmData20240317:     newYmData20240317(db, opts...),
		YmData20240318:     newYmData20240318(db, opts...),
		YmData20240319:     newYmData20240319(db, opts...),
		YmData20240320:     newYmData20240320(db, opts...),
		YmData20240321:     newYmData20240321(db, opts...),
		YmData20240322:     newYmData20240322(db, opts...),
		YmData20240323:     newYmData20240323(db, opts...),
		YmData20240324:     newYmData20240324(db, opts...),
		YmData20240325:     newYmData20240325(db, opts...),
		YmData20240326:     newYmData20240326(db, opts...),
		YmData20240327:     newYmData20240327(db, opts...),
		YmData20240328:     newYmData20240328(db, opts...),
		YmData20240329:     newYmData20240329(db, opts...),
		YmData20240330:     newYmData20240330(db, opts...),
		YmData20240331:     newYmData20240331(db, opts...),
		YmData20240401:     newYmData20240401(db, opts...),
		YmData20240402:     newYmData20240402(db, opts...),
		YmData20240403:     newYmData20240403(db, opts...),
		YmData20240404:     newYmData20240404(db, opts...),
		YmData20240405:     newYmData20240405(db, opts...),
		YmData20240406:     newYmData20240406(db, opts...),
		YmData20240407:     newYmData20240407(db, opts...),
		YmData20240408:     newYmData20240408(db, opts...),
		YmData20240409:     newYmData20240409(db, opts...),
		YmData20240410:     newYmData20240410(db, opts...),
		YmData20240411:     newYmData20240411(db, opts...),
		YmData20240412:     newYmData20240412(db, opts...),
		YmData20240413:     newYmData20240413(db, opts...),
		YmData20240414:     newYmData20240414(db, opts...),
		YmData20240415:     newYmData20240415(db, opts...),
		YmData20240416:     newYmData20240416(db, opts...),
		YmData20240417:     newYmData20240417(db, opts...),
		YmData20240418:     newYmData20240418(db, opts...),
		YmData20240419:     newYmData20240419(db, opts...),
		YmData20240420:     newYmData20240420(db, opts...),
		YmData20240421:     newYmData20240421(db, opts...),
		YmData20240422:     newYmData20240422(db, opts...),
		YmData20240423:     newYmData20240423(db, opts...),
		YmData20240424:     newYmData20240424(db, opts...),
		YmData20240425:     newYmData20240425(db, opts...),
		YmData20240426:     newYmData20240426(db, opts...),
		YmData20240427:     newYmData20240427(db, opts...),
		YmData20240428:     newYmData20240428(db, opts...),
		YmData20240429:     newYmData20240429(db, opts...),
		YmData20240430:     newYmData20240430(db, opts...),
		YmData20240501:     newYmData20240501(db, opts...),
		YmData20240502:     newYmData20240502(db, opts...),
		YmData20240503:     newYmData20240503(db, opts...),
		YmData20240504:     newYmData20240504(db, opts...),
		YmData20240505:     newYmData20240505(db, opts...),
		YmData20240506:     newYmData20240506(db, opts...),
		YmData20240507:     newYmData20240507(db, opts...),
		YmData20240508:     newYmData20240508(db, opts...),
		YmData20240509:     newYmData20240509(db, opts...),
		YmData20240510:     newYmData20240510(db, opts...),
		YmData20240511:     newYmData20240511(db, opts...),
		YmData20240512:     newYmData20240512(db, opts...),
		YmData20240513:     newYmData20240513(db, opts...),
		YmData20240514:     newYmData20240514(db, opts...),
		YmData20240515:     newYmData20240515(db, opts...),
		YmData20240516:     newYmData20240516(db, opts...),
		YmData20240517:     newYmData20240517(db, opts...),
		YmData20240518:     newYmData20240518(db, opts...),
		YmData20240519:     newYmData20240519(db, opts...),
		YmData20240520:     newYmData20240520(db, opts...),
		YmData20240521:     newYmData20240521(db, opts...),
		YmData20240522:     newYmData20240522(db, opts...),
		YmData20240523:     newYmData20240523(db, opts...),
		YmData20240524:     newYmData20240524(db, opts...),
		YmData20240525:     newYmData20240525(db, opts...),
		YmData20240526:     newYmData20240526(db, opts...),
		YmData20240527:     newYmData20240527(db, opts...),
		YmData20240528:     newYmData20240528(db, opts...),
		YmData20240529:     newYmData20240529(db, opts...),
		YmData20240530:     newYmData20240530(db, opts...),
		YmData20240531:     newYmData20240531(db, opts...),
		YmData20240601:     newYmData20240601(db, opts...),
		YmData20240602:     newYmData20240602(db, opts...),
		YmData20240603:     newYmData20240603(db, opts...),
		YmData20240604:     newYmData20240604(db, opts...),
		YmData20240605:     newYmData20240605(db, opts...),
		YmData20240606:     newYmData20240606(db, opts...),
		YmData20240607:     newYmData20240607(db, opts...),
		YmData20240608:     newYmData20240608(db, opts...),
		YmData20240609:     newYmData20240609(db, opts...),
		YmData20240610:     newYmData20240610(db, opts...),
		YmData20240611:     newYmData20240611(db, opts...),
		YmData20240612:     newYmData20240612(db, opts...),
		YmData20240613:     newYmData20240613(db, opts...),
		YmData20240614:     newYmData20240614(db, opts...),
		YmData20240615:     newYmData20240615(db, opts...),
		YmData20240616:     newYmData20240616(db, opts...),
		YmData20240617:     newYmData20240617(db, opts...),
		YmData20240618:     newYmData20240618(db, opts...),
		YmDatum:            newYmDatum(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	DimensionReference dimensionReference
	YmData20240101     ymData20240101
	YmData20240102     ymData20240102
	YmData20240103     ymData20240103
	YmData20240104     ymData20240104
	YmData20240105     ymData20240105
	YmData20240106     ymData20240106
	YmData20240107     ymData20240107
	YmData20240108     ymData20240108
	YmData20240109     ymData20240109
	YmData20240110     ymData20240110
	YmData20240111     ymData20240111
	YmData20240112     ymData20240112
	YmData20240113     ymData20240113
	YmData20240114     ymData20240114
	YmData20240115     ymData20240115
	YmData20240116     ymData20240116
	YmData20240117     ymData20240117
	YmData20240118     ymData20240118
	YmData20240119     ymData20240119
	YmData20240120     ymData20240120
	YmData20240121     ymData20240121
	YmData20240122     ymData20240122
	YmData20240123     ymData20240123
	YmData20240124     ymData20240124
	YmData20240125     ymData20240125
	YmData20240126     ymData20240126
	YmData20240127     ymData20240127
	YmData20240128     ymData20240128
	YmData20240129     ymData20240129
	YmData20240130     ymData20240130
	YmData20240131     ymData20240131
	YmData20240201     ymData20240201
	YmData20240202     ymData20240202
	YmData20240203     ymData20240203
	YmData20240204     ymData20240204
	YmData20240205     ymData20240205
	YmData20240206     ymData20240206
	YmData20240207     ymData20240207
	YmData20240208     ymData20240208
	YmData20240209     ymData20240209
	YmData20240210     ymData20240210
	YmData20240211     ymData20240211
	YmData20240212     ymData20240212
	YmData20240213     ymData20240213
	YmData20240214     ymData20240214
	YmData20240215     ymData20240215
	YmData20240216     ymData20240216
	YmData20240217     ymData20240217
	YmData20240218     ymData20240218
	YmData20240219     ymData20240219
	YmData20240220     ymData20240220
	YmData20240221     ymData20240221
	YmData20240222     ymData20240222
	YmData20240223     ymData20240223
	YmData20240224     ymData20240224
	YmData20240225     ymData20240225
	YmData20240226     ymData20240226
	YmData20240227     ymData20240227
	YmData20240228     ymData20240228
	YmData20240229     ymData20240229
	YmData20240301     ymData20240301
	YmData20240302     ymData20240302
	YmData20240303     ymData20240303
	YmData20240304     ymData20240304
	YmData20240305     ymData20240305
	YmData20240306     ymData20240306
	YmData20240307     ymData20240307
	YmData20240308     ymData20240308
	YmData20240309     ymData20240309
	YmData20240310     ymData20240310
	YmData20240311     ymData20240311
	YmData20240312     ymData20240312
	YmData20240313     ymData20240313
	YmData20240314     ymData20240314
	YmData20240315     ymData20240315
	YmData20240316     ymData20240316
	YmData20240317     ymData20240317
	YmData20240318     ymData20240318
	YmData20240319     ymData20240319
	YmData20240320     ymData20240320
	YmData20240321     ymData20240321
	YmData20240322     ymData20240322
	YmData20240323     ymData20240323
	YmData20240324     ymData20240324
	YmData20240325     ymData20240325
	YmData20240326     ymData20240326
	YmData20240327     ymData20240327
	YmData20240328     ymData20240328
	YmData20240329     ymData20240329
	YmData20240330     ymData20240330
	YmData20240331     ymData20240331
	YmData20240401     ymData20240401
	YmData20240402     ymData20240402
	YmData20240403     ymData20240403
	YmData20240404     ymData20240404
	YmData20240405     ymData20240405
	YmData20240406     ymData20240406
	YmData20240407     ymData20240407
	YmData20240408     ymData20240408
	YmData20240409     ymData20240409
	YmData20240410     ymData20240410
	YmData20240411     ymData20240411
	YmData20240412     ymData20240412
	YmData20240413     ymData20240413
	YmData20240414     ymData20240414
	YmData20240415     ymData20240415
	YmData20240416     ymData20240416
	YmData20240417     ymData20240417
	YmData20240418     ymData20240418
	YmData20240419     ymData20240419
	YmData20240420     ymData20240420
	YmData20240421     ymData20240421
	YmData20240422     ymData20240422
	YmData20240423     ymData20240423
	YmData20240424     ymData20240424
	YmData20240425     ymData20240425
	YmData20240426     ymData20240426
	YmData20240427     ymData20240427
	YmData20240428     ymData20240428
	YmData20240429     ymData20240429
	YmData20240430     ymData20240430
	YmData20240501     ymData20240501
	YmData20240502     ymData20240502
	YmData20240503     ymData20240503
	YmData20240504     ymData20240504
	YmData20240505     ymData20240505
	YmData20240506     ymData20240506
	YmData20240507     ymData20240507
	YmData20240508     ymData20240508
	YmData20240509     ymData20240509
	YmData20240510     ymData20240510
	YmData20240511     ymData20240511
	YmData20240512     ymData20240512
	YmData20240513     ymData20240513
	YmData20240514     ymData20240514
	YmData20240515     ymData20240515
	YmData20240516     ymData20240516
	YmData20240517     ymData20240517
	YmData20240518     ymData20240518
	YmData20240519     ymData20240519
	YmData20240520     ymData20240520
	YmData20240521     ymData20240521
	YmData20240522     ymData20240522
	YmData20240523     ymData20240523
	YmData20240524     ymData20240524
	YmData20240525     ymData20240525
	YmData20240526     ymData20240526
	YmData20240527     ymData20240527
	YmData20240528     ymData20240528
	YmData20240529     ymData20240529
	YmData20240530     ymData20240530
	YmData20240531     ymData20240531
	YmData20240601     ymData20240601
	YmData20240602     ymData20240602
	YmData20240603     ymData20240603
	YmData20240604     ymData20240604
	YmData20240605     ymData20240605
	YmData20240606     ymData20240606
	YmData20240607     ymData20240607
	YmData20240608     ymData20240608
	YmData20240609     ymData20240609
	YmData20240610     ymData20240610
	YmData20240611     ymData20240611
	YmData20240612     ymData20240612
	YmData20240613     ymData20240613
	YmData20240614     ymData20240614
	YmData20240615     ymData20240615
	YmData20240616     ymData20240616
	YmData20240617     ymData20240617
	YmData20240618     ymData20240618
	YmDatum            ymDatum
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		DimensionReference: q.DimensionReference.clone(db),
		YmData20240101:     q.YmData20240101.clone(db),
		YmData20240102:     q.YmData20240102.clone(db),
		YmData20240103:     q.YmData20240103.clone(db),
		YmData20240104:     q.YmData20240104.clone(db),
		YmData20240105:     q.YmData20240105.clone(db),
		YmData20240106:     q.YmData20240106.clone(db),
		YmData20240107:     q.YmData20240107.clone(db),
		YmData20240108:     q.YmData20240108.clone(db),
		YmData20240109:     q.YmData20240109.clone(db),
		YmData20240110:     q.YmData20240110.clone(db),
		YmData20240111:     q.YmData20240111.clone(db),
		YmData20240112:     q.YmData20240112.clone(db),
		YmData20240113:     q.YmData20240113.clone(db),
		YmData20240114:     q.YmData20240114.clone(db),
		YmData20240115:     q.YmData20240115.clone(db),
		YmData20240116:     q.YmData20240116.clone(db),
		YmData20240117:     q.YmData20240117.clone(db),
		YmData20240118:     q.YmData20240118.clone(db),
		YmData20240119:     q.YmData20240119.clone(db),
		YmData20240120:     q.YmData20240120.clone(db),
		YmData20240121:     q.YmData20240121.clone(db),
		YmData20240122:     q.YmData20240122.clone(db),
		YmData20240123:     q.YmData20240123.clone(db),
		YmData20240124:     q.YmData20240124.clone(db),
		YmData20240125:     q.YmData20240125.clone(db),
		YmData20240126:     q.YmData20240126.clone(db),
		YmData20240127:     q.YmData20240127.clone(db),
		YmData20240128:     q.YmData20240128.clone(db),
		YmData20240129:     q.YmData20240129.clone(db),
		YmData20240130:     q.YmData20240130.clone(db),
		YmData20240131:     q.YmData20240131.clone(db),
		YmData20240201:     q.YmData20240201.clone(db),
		YmData20240202:     q.YmData20240202.clone(db),
		YmData20240203:     q.YmData20240203.clone(db),
		YmData20240204:     q.YmData20240204.clone(db),
		YmData20240205:     q.YmData20240205.clone(db),
		YmData20240206:     q.YmData20240206.clone(db),
		YmData20240207:     q.YmData20240207.clone(db),
		YmData20240208:     q.YmData20240208.clone(db),
		YmData20240209:     q.YmData20240209.clone(db),
		YmData20240210:     q.YmData20240210.clone(db),
		YmData20240211:     q.YmData20240211.clone(db),
		YmData20240212:     q.YmData20240212.clone(db),
		YmData20240213:     q.YmData20240213.clone(db),
		YmData20240214:     q.YmData20240214.clone(db),
		YmData20240215:     q.YmData20240215.clone(db),
		YmData20240216:     q.YmData20240216.clone(db),
		YmData20240217:     q.YmData20240217.clone(db),
		YmData20240218:     q.YmData20240218.clone(db),
		YmData20240219:     q.YmData20240219.clone(db),
		YmData20240220:     q.YmData20240220.clone(db),
		YmData20240221:     q.YmData20240221.clone(db),
		YmData20240222:     q.YmData20240222.clone(db),
		YmData20240223:     q.YmData20240223.clone(db),
		YmData20240224:     q.YmData20240224.clone(db),
		YmData20240225:     q.YmData20240225.clone(db),
		YmData20240226:     q.YmData20240226.clone(db),
		YmData20240227:     q.YmData20240227.clone(db),
		YmData20240228:     q.YmData20240228.clone(db),
		YmData20240229:     q.YmData20240229.clone(db),
		YmData20240301:     q.YmData20240301.clone(db),
		YmData20240302:     q.YmData20240302.clone(db),
		YmData20240303:     q.YmData20240303.clone(db),
		YmData20240304:     q.YmData20240304.clone(db),
		YmData20240305:     q.YmData20240305.clone(db),
		YmData20240306:     q.YmData20240306.clone(db),
		YmData20240307:     q.YmData20240307.clone(db),
		YmData20240308:     q.YmData20240308.clone(db),
		YmData20240309:     q.YmData20240309.clone(db),
		YmData20240310:     q.YmData20240310.clone(db),
		YmData20240311:     q.YmData20240311.clone(db),
		YmData20240312:     q.YmData20240312.clone(db),
		YmData20240313:     q.YmData20240313.clone(db),
		YmData20240314:     q.YmData20240314.clone(db),
		YmData20240315:     q.YmData20240315.clone(db),
		YmData20240316:     q.YmData20240316.clone(db),
		YmData20240317:     q.YmData20240317.clone(db),
		YmData20240318:     q.YmData20240318.clone(db),
		YmData20240319:     q.YmData20240319.clone(db),
		YmData20240320:     q.YmData20240320.clone(db),
		YmData20240321:     q.YmData20240321.clone(db),
		YmData20240322:     q.YmData20240322.clone(db),
		YmData20240323:     q.YmData20240323.clone(db),
		YmData20240324:     q.YmData20240324.clone(db),
		YmData20240325:     q.YmData20240325.clone(db),
		YmData20240326:     q.YmData20240326.clone(db),
		YmData20240327:     q.YmData20240327.clone(db),
		YmData20240328:     q.YmData20240328.clone(db),
		YmData20240329:     q.YmData20240329.clone(db),
		YmData20240330:     q.YmData20240330.clone(db),
		YmData20240331:     q.YmData20240331.clone(db),
		YmData20240401:     q.YmData20240401.clone(db),
		YmData20240402:     q.YmData20240402.clone(db),
		YmData20240403:     q.YmData20240403.clone(db),
		YmData20240404:     q.YmData20240404.clone(db),
		YmData20240405:     q.YmData20240405.clone(db),
		YmData20240406:     q.YmData20240406.clone(db),
		YmData20240407:     q.YmData20240407.clone(db),
		YmData20240408:     q.YmData20240408.clone(db),
		YmData20240409:     q.YmData20240409.clone(db),
		YmData20240410:     q.YmData20240410.clone(db),
		YmData20240411:     q.YmData20240411.clone(db),
		YmData20240412:     q.YmData20240412.clone(db),
		YmData20240413:     q.YmData20240413.clone(db),
		YmData20240414:     q.YmData20240414.clone(db),
		YmData20240415:     q.YmData20240415.clone(db),
		YmData20240416:     q.YmData20240416.clone(db),
		YmData20240417:     q.YmData20240417.clone(db),
		YmData20240418:     q.YmData20240418.clone(db),
		YmData20240419:     q.YmData20240419.clone(db),
		YmData20240420:     q.YmData20240420.clone(db),
		YmData20240421:     q.YmData20240421.clone(db),
		YmData20240422:     q.YmData20240422.clone(db),
		YmData20240423:     q.YmData20240423.clone(db),
		YmData20240424:     q.YmData20240424.clone(db),
		YmData20240425:     q.YmData20240425.clone(db),
		YmData20240426:     q.YmData20240426.clone(db),
		YmData20240427:     q.YmData20240427.clone(db),
		YmData20240428:     q.YmData20240428.clone(db),
		YmData20240429:     q.YmData20240429.clone(db),
		YmData20240430:     q.YmData20240430.clone(db),
		YmData20240501:     q.YmData20240501.clone(db),
		YmData20240502:     q.YmData20240502.clone(db),
		YmData20240503:     q.YmData20240503.clone(db),
		YmData20240504:     q.YmData20240504.clone(db),
		YmData20240505:     q.YmData20240505.clone(db),
		YmData20240506:     q.YmData20240506.clone(db),
		YmData20240507:     q.YmData20240507.clone(db),
		YmData20240508:     q.YmData20240508.clone(db),
		YmData20240509:     q.YmData20240509.clone(db),
		YmData20240510:     q.YmData20240510.clone(db),
		YmData20240511:     q.YmData20240511.clone(db),
		YmData20240512:     q.YmData20240512.clone(db),
		YmData20240513:     q.YmData20240513.clone(db),
		YmData20240514:     q.YmData20240514.clone(db),
		YmData20240515:     q.YmData20240515.clone(db),
		YmData20240516:     q.YmData20240516.clone(db),
		YmData20240517:     q.YmData20240517.clone(db),
		YmData20240518:     q.YmData20240518.clone(db),
		YmData20240519:     q.YmData20240519.clone(db),
		YmData20240520:     q.YmData20240520.clone(db),
		YmData20240521:     q.YmData20240521.clone(db),
		YmData20240522:     q.YmData20240522.clone(db),
		YmData20240523:     q.YmData20240523.clone(db),
		YmData20240524:     q.YmData20240524.clone(db),
		YmData20240525:     q.YmData20240525.clone(db),
		YmData20240526:     q.YmData20240526.clone(db),
		YmData20240527:     q.YmData20240527.clone(db),
		YmData20240528:     q.YmData20240528.clone(db),
		YmData20240529:     q.YmData20240529.clone(db),
		YmData20240530:     q.YmData20240530.clone(db),
		YmData20240531:     q.YmData20240531.clone(db),
		YmData20240601:     q.YmData20240601.clone(db),
		YmData20240602:     q.YmData20240602.clone(db),
		YmData20240603:     q.YmData20240603.clone(db),
		YmData20240604:     q.YmData20240604.clone(db),
		YmData20240605:     q.YmData20240605.clone(db),
		YmData20240606:     q.YmData20240606.clone(db),
		YmData20240607:     q.YmData20240607.clone(db),
		YmData20240608:     q.YmData20240608.clone(db),
		YmData20240609:     q.YmData20240609.clone(db),
		YmData20240610:     q.YmData20240610.clone(db),
		YmData20240611:     q.YmData20240611.clone(db),
		YmData20240612:     q.YmData20240612.clone(db),
		YmData20240613:     q.YmData20240613.clone(db),
		YmData20240614:     q.YmData20240614.clone(db),
		YmData20240615:     q.YmData20240615.clone(db),
		YmData20240616:     q.YmData20240616.clone(db),
		YmData20240617:     q.YmData20240617.clone(db),
		YmData20240618:     q.YmData20240618.clone(db),
		YmDatum:            q.YmDatum.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		DimensionReference: q.DimensionReference.replaceDB(db),
		YmData20240101:     q.YmData20240101.replaceDB(db),
		YmData20240102:     q.YmData20240102.replaceDB(db),
		YmData20240103:     q.YmData20240103.replaceDB(db),
		YmData20240104:     q.YmData20240104.replaceDB(db),
		YmData20240105:     q.YmData20240105.replaceDB(db),
		YmData20240106:     q.YmData20240106.replaceDB(db),
		YmData20240107:     q.YmData20240107.replaceDB(db),
		YmData20240108:     q.YmData20240108.replaceDB(db),
		YmData20240109:     q.YmData20240109.replaceDB(db),
		YmData20240110:     q.YmData20240110.replaceDB(db),
		YmData20240111:     q.YmData20240111.replaceDB(db),
		YmData20240112:     q.YmData20240112.replaceDB(db),
		YmData20240113:     q.YmData20240113.replaceDB(db),
		YmData20240114:     q.YmData20240114.replaceDB(db),
		YmData20240115:     q.YmData20240115.replaceDB(db),
		YmData20240116:     q.YmData20240116.replaceDB(db),
		YmData20240117:     q.YmData20240117.replaceDB(db),
		YmData20240118:     q.YmData20240118.replaceDB(db),
		YmData20240119:     q.YmData20240119.replaceDB(db),
		YmData20240120:     q.YmData20240120.replaceDB(db),
		YmData20240121:     q.YmData20240121.replaceDB(db),
		YmData20240122:     q.YmData20240122.replaceDB(db),
		YmData20240123:     q.YmData20240123.replaceDB(db),
		YmData20240124:     q.YmData20240124.replaceDB(db),
		YmData20240125:     q.YmData20240125.replaceDB(db),
		YmData20240126:     q.YmData20240126.replaceDB(db),
		YmData20240127:     q.YmData20240127.replaceDB(db),
		YmData20240128:     q.YmData20240128.replaceDB(db),
		YmData20240129:     q.YmData20240129.replaceDB(db),
		YmData20240130:     q.YmData20240130.replaceDB(db),
		YmData20240131:     q.YmData20240131.replaceDB(db),
		YmData20240201:     q.YmData20240201.replaceDB(db),
		YmData20240202:     q.YmData20240202.replaceDB(db),
		YmData20240203:     q.YmData20240203.replaceDB(db),
		YmData20240204:     q.YmData20240204.replaceDB(db),
		YmData20240205:     q.YmData20240205.replaceDB(db),
		YmData20240206:     q.YmData20240206.replaceDB(db),
		YmData20240207:     q.YmData20240207.replaceDB(db),
		YmData20240208:     q.YmData20240208.replaceDB(db),
		YmData20240209:     q.YmData20240209.replaceDB(db),
		YmData20240210:     q.YmData20240210.replaceDB(db),
		YmData20240211:     q.YmData20240211.replaceDB(db),
		YmData20240212:     q.YmData20240212.replaceDB(db),
		YmData20240213:     q.YmData20240213.replaceDB(db),
		YmData20240214:     q.YmData20240214.replaceDB(db),
		YmData20240215:     q.YmData20240215.replaceDB(db),
		YmData20240216:     q.YmData20240216.replaceDB(db),
		YmData20240217:     q.YmData20240217.replaceDB(db),
		YmData20240218:     q.YmData20240218.replaceDB(db),
		YmData20240219:     q.YmData20240219.replaceDB(db),
		YmData20240220:     q.YmData20240220.replaceDB(db),
		YmData20240221:     q.YmData20240221.replaceDB(db),
		YmData20240222:     q.YmData20240222.replaceDB(db),
		YmData20240223:     q.YmData20240223.replaceDB(db),
		YmData20240224:     q.YmData20240224.replaceDB(db),
		YmData20240225:     q.YmData20240225.replaceDB(db),
		YmData20240226:     q.YmData20240226.replaceDB(db),
		YmData20240227:     q.YmData20240227.replaceDB(db),
		YmData20240228:     q.YmData20240228.replaceDB(db),
		YmData20240229:     q.YmData20240229.replaceDB(db),
		YmData20240301:     q.YmData20240301.replaceDB(db),
		YmData20240302:     q.YmData20240302.replaceDB(db),
		YmData20240303:     q.YmData20240303.replaceDB(db),
		YmData20240304:     q.YmData20240304.replaceDB(db),
		YmData20240305:     q.YmData20240305.replaceDB(db),
		YmData20240306:     q.YmData20240306.replaceDB(db),
		YmData20240307:     q.YmData20240307.replaceDB(db),
		YmData20240308:     q.YmData20240308.replaceDB(db),
		YmData20240309:     q.YmData20240309.replaceDB(db),
		YmData20240310:     q.YmData20240310.replaceDB(db),
		YmData20240311:     q.YmData20240311.replaceDB(db),
		YmData20240312:     q.YmData20240312.replaceDB(db),
		YmData20240313:     q.YmData20240313.replaceDB(db),
		YmData20240314:     q.YmData20240314.replaceDB(db),
		YmData20240315:     q.YmData20240315.replaceDB(db),
		YmData20240316:     q.YmData20240316.replaceDB(db),
		YmData20240317:     q.YmData20240317.replaceDB(db),
		YmData20240318:     q.YmData20240318.replaceDB(db),
		YmData20240319:     q.YmData20240319.replaceDB(db),
		YmData20240320:     q.YmData20240320.replaceDB(db),
		YmData20240321:     q.YmData20240321.replaceDB(db),
		YmData20240322:     q.YmData20240322.replaceDB(db),
		YmData20240323:     q.YmData20240323.replaceDB(db),
		YmData20240324:     q.YmData20240324.replaceDB(db),
		YmData20240325:     q.YmData20240325.replaceDB(db),
		YmData20240326:     q.YmData20240326.replaceDB(db),
		YmData20240327:     q.YmData20240327.replaceDB(db),
		YmData20240328:     q.YmData20240328.replaceDB(db),
		YmData20240329:     q.YmData20240329.replaceDB(db),
		YmData20240330:     q.YmData20240330.replaceDB(db),
		YmData20240331:     q.YmData20240331.replaceDB(db),
		YmData20240401:     q.YmData20240401.replaceDB(db),
		YmData20240402:     q.YmData20240402.replaceDB(db),
		YmData20240403:     q.YmData20240403.replaceDB(db),
		YmData20240404:     q.YmData20240404.replaceDB(db),
		YmData20240405:     q.YmData20240405.replaceDB(db),
		YmData20240406:     q.YmData20240406.replaceDB(db),
		YmData20240407:     q.YmData20240407.replaceDB(db),
		YmData20240408:     q.YmData20240408.replaceDB(db),
		YmData20240409:     q.YmData20240409.replaceDB(db),
		YmData20240410:     q.YmData20240410.replaceDB(db),
		YmData20240411:     q.YmData20240411.replaceDB(db),
		YmData20240412:     q.YmData20240412.replaceDB(db),
		YmData20240413:     q.YmData20240413.replaceDB(db),
		YmData20240414:     q.YmData20240414.replaceDB(db),
		YmData20240415:     q.YmData20240415.replaceDB(db),
		YmData20240416:     q.YmData20240416.replaceDB(db),
		YmData20240417:     q.YmData20240417.replaceDB(db),
		YmData20240418:     q.YmData20240418.replaceDB(db),
		YmData20240419:     q.YmData20240419.replaceDB(db),
		YmData20240420:     q.YmData20240420.replaceDB(db),
		YmData20240421:     q.YmData20240421.replaceDB(db),
		YmData20240422:     q.YmData20240422.replaceDB(db),
		YmData20240423:     q.YmData20240423.replaceDB(db),
		YmData20240424:     q.YmData20240424.replaceDB(db),
		YmData20240425:     q.YmData20240425.replaceDB(db),
		YmData20240426:     q.YmData20240426.replaceDB(db),
		YmData20240427:     q.YmData20240427.replaceDB(db),
		YmData20240428:     q.YmData20240428.replaceDB(db),
		YmData20240429:     q.YmData20240429.replaceDB(db),
		YmData20240430:     q.YmData20240430.replaceDB(db),
		YmData20240501:     q.YmData20240501.replaceDB(db),
		YmData20240502:     q.YmData20240502.replaceDB(db),
		YmData20240503:     q.YmData20240503.replaceDB(db),
		YmData20240504:     q.YmData20240504.replaceDB(db),
		YmData20240505:     q.YmData20240505.replaceDB(db),
		YmData20240506:     q.YmData20240506.replaceDB(db),
		YmData20240507:     q.YmData20240507.replaceDB(db),
		YmData20240508:     q.YmData20240508.replaceDB(db),
		YmData20240509:     q.YmData20240509.replaceDB(db),
		YmData20240510:     q.YmData20240510.replaceDB(db),
		YmData20240511:     q.YmData20240511.replaceDB(db),
		YmData20240512:     q.YmData20240512.replaceDB(db),
		YmData20240513:     q.YmData20240513.replaceDB(db),
		YmData20240514:     q.YmData20240514.replaceDB(db),
		YmData20240515:     q.YmData20240515.replaceDB(db),
		YmData20240516:     q.YmData20240516.replaceDB(db),
		YmData20240517:     q.YmData20240517.replaceDB(db),
		YmData20240518:     q.YmData20240518.replaceDB(db),
		YmData20240519:     q.YmData20240519.replaceDB(db),
		YmData20240520:     q.YmData20240520.replaceDB(db),
		YmData20240521:     q.YmData20240521.replaceDB(db),
		YmData20240522:     q.YmData20240522.replaceDB(db),
		YmData20240523:     q.YmData20240523.replaceDB(db),
		YmData20240524:     q.YmData20240524.replaceDB(db),
		YmData20240525:     q.YmData20240525.replaceDB(db),
		YmData20240526:     q.YmData20240526.replaceDB(db),
		YmData20240527:     q.YmData20240527.replaceDB(db),
		YmData20240528:     q.YmData20240528.replaceDB(db),
		YmData20240529:     q.YmData20240529.replaceDB(db),
		YmData20240530:     q.YmData20240530.replaceDB(db),
		YmData20240531:     q.YmData20240531.replaceDB(db),
		YmData20240601:     q.YmData20240601.replaceDB(db),
		YmData20240602:     q.YmData20240602.replaceDB(db),
		YmData20240603:     q.YmData20240603.replaceDB(db),
		YmData20240604:     q.YmData20240604.replaceDB(db),
		YmData20240605:     q.YmData20240605.replaceDB(db),
		YmData20240606:     q.YmData20240606.replaceDB(db),
		YmData20240607:     q.YmData20240607.replaceDB(db),
		YmData20240608:     q.YmData20240608.replaceDB(db),
		YmData20240609:     q.YmData20240609.replaceDB(db),
		YmData20240610:     q.YmData20240610.replaceDB(db),
		YmData20240611:     q.YmData20240611.replaceDB(db),
		YmData20240612:     q.YmData20240612.replaceDB(db),
		YmData20240613:     q.YmData20240613.replaceDB(db),
		YmData20240614:     q.YmData20240614.replaceDB(db),
		YmData20240615:     q.YmData20240615.replaceDB(db),
		YmData20240616:     q.YmData20240616.replaceDB(db),
		YmData20240617:     q.YmData20240617.replaceDB(db),
		YmData20240618:     q.YmData20240618.replaceDB(db),
		YmDatum:            q.YmDatum.replaceDB(db),
	}
}

type queryCtx struct {
	DimensionReference IDimensionReferenceDo
	YmData20240101     IYmData20240101Do
	YmData20240102     IYmData20240102Do
	YmData20240103     IYmData20240103Do
	YmData20240104     IYmData20240104Do
	YmData20240105     IYmData20240105Do
	YmData20240106     IYmData20240106Do
	YmData20240107     IYmData20240107Do
	YmData20240108     IYmData20240108Do
	YmData20240109     IYmData20240109Do
	YmData20240110     IYmData20240110Do
	YmData20240111     IYmData20240111Do
	YmData20240112     IYmData20240112Do
	YmData20240113     IYmData20240113Do
	YmData20240114     IYmData20240114Do
	YmData20240115     IYmData20240115Do
	YmData20240116     IYmData20240116Do
	YmData20240117     IYmData20240117Do
	YmData20240118     IYmData20240118Do
	YmData20240119     IYmData20240119Do
	YmData20240120     IYmData20240120Do
	YmData20240121     IYmData20240121Do
	YmData20240122     IYmData20240122Do
	YmData20240123     IYmData20240123Do
	YmData20240124     IYmData20240124Do
	YmData20240125     IYmData20240125Do
	YmData20240126     IYmData20240126Do
	YmData20240127     IYmData20240127Do
	YmData20240128     IYmData20240128Do
	YmData20240129     IYmData20240129Do
	YmData20240130     IYmData20240130Do
	YmData20240131     IYmData20240131Do
	YmData20240201     IYmData20240201Do
	YmData20240202     IYmData20240202Do
	YmData20240203     IYmData20240203Do
	YmData20240204     IYmData20240204Do
	YmData20240205     IYmData20240205Do
	YmData20240206     IYmData20240206Do
	YmData20240207     IYmData20240207Do
	YmData20240208     IYmData20240208Do
	YmData20240209     IYmData20240209Do
	YmData20240210     IYmData20240210Do
	YmData20240211     IYmData20240211Do
	YmData20240212     IYmData20240212Do
	YmData20240213     IYmData20240213Do
	YmData20240214     IYmData20240214Do
	YmData20240215     IYmData20240215Do
	YmData20240216     IYmData20240216Do
	YmData20240217     IYmData20240217Do
	YmData20240218     IYmData20240218Do
	YmData20240219     IYmData20240219Do
	YmData20240220     IYmData20240220Do
	YmData20240221     IYmData20240221Do
	YmData20240222     IYmData20240222Do
	YmData20240223     IYmData20240223Do
	YmData20240224     IYmData20240224Do
	YmData20240225     IYmData20240225Do
	YmData20240226     IYmData20240226Do
	YmData20240227     IYmData20240227Do
	YmData20240228     IYmData20240228Do
	YmData20240229     IYmData20240229Do
	YmData20240301     IYmData20240301Do
	YmData20240302     IYmData20240302Do
	YmData20240303     IYmData20240303Do
	YmData20240304     IYmData20240304Do
	YmData20240305     IYmData20240305Do
	YmData20240306     IYmData20240306Do
	YmData20240307     IYmData20240307Do
	YmData20240308     IYmData20240308Do
	YmData20240309     IYmData20240309Do
	YmData20240310     IYmData20240310Do
	YmData20240311     IYmData20240311Do
	YmData20240312     IYmData20240312Do
	YmData20240313     IYmData20240313Do
	YmData20240314     IYmData20240314Do
	YmData20240315     IYmData20240315Do
	YmData20240316     IYmData20240316Do
	YmData20240317     IYmData20240317Do
	YmData20240318     IYmData20240318Do
	YmData20240319     IYmData20240319Do
	YmData20240320     IYmData20240320Do
	YmData20240321     IYmData20240321Do
	YmData20240322     IYmData20240322Do
	YmData20240323     IYmData20240323Do
	YmData20240324     IYmData20240324Do
	YmData20240325     IYmData20240325Do
	YmData20240326     IYmData20240326Do
	YmData20240327     IYmData20240327Do
	YmData20240328     IYmData20240328Do
	YmData20240329     IYmData20240329Do
	YmData20240330     IYmData20240330Do
	YmData20240331     IYmData20240331Do
	YmData20240401     IYmData20240401Do
	YmData20240402     IYmData20240402Do
	YmData20240403     IYmData20240403Do
	YmData20240404     IYmData20240404Do
	YmData20240405     IYmData20240405Do
	YmData20240406     IYmData20240406Do
	YmData20240407     IYmData20240407Do
	YmData20240408     IYmData20240408Do
	YmData20240409     IYmData20240409Do
	YmData20240410     IYmData20240410Do
	YmData20240411     IYmData20240411Do
	YmData20240412     IYmData20240412Do
	YmData20240413     IYmData20240413Do
	YmData20240414     IYmData20240414Do
	YmData20240415     IYmData20240415Do
	YmData20240416     IYmData20240416Do
	YmData20240417     IYmData20240417Do
	YmData20240418     IYmData20240418Do
	YmData20240419     IYmData20240419Do
	YmData20240420     IYmData20240420Do
	YmData20240421     IYmData20240421Do
	YmData20240422     IYmData20240422Do
	YmData20240423     IYmData20240423Do
	YmData20240424     IYmData20240424Do
	YmData20240425     IYmData20240425Do
	YmData20240426     IYmData20240426Do
	YmData20240427     IYmData20240427Do
	YmData20240428     IYmData20240428Do
	YmData20240429     IYmData20240429Do
	YmData20240430     IYmData20240430Do
	YmData20240501     IYmData20240501Do
	YmData20240502     IYmData20240502Do
	YmData20240503     IYmData20240503Do
	YmData20240504     IYmData20240504Do
	YmData20240505     IYmData20240505Do
	YmData20240506     IYmData20240506Do
	YmData20240507     IYmData20240507Do
	YmData20240508     IYmData20240508Do
	YmData20240509     IYmData20240509Do
	YmData20240510     IYmData20240510Do
	YmData20240511     IYmData20240511Do
	YmData20240512     IYmData20240512Do
	YmData20240513     IYmData20240513Do
	YmData20240514     IYmData20240514Do
	YmData20240515     IYmData20240515Do
	YmData20240516     IYmData20240516Do
	YmData20240517     IYmData20240517Do
	YmData20240518     IYmData20240518Do
	YmData20240519     IYmData20240519Do
	YmData20240520     IYmData20240520Do
	YmData20240521     IYmData20240521Do
	YmData20240522     IYmData20240522Do
	YmData20240523     IYmData20240523Do
	YmData20240524     IYmData20240524Do
	YmData20240525     IYmData20240525Do
	YmData20240526     IYmData20240526Do
	YmData20240527     IYmData20240527Do
	YmData20240528     IYmData20240528Do
	YmData20240529     IYmData20240529Do
	YmData20240530     IYmData20240530Do
	YmData20240531     IYmData20240531Do
	YmData20240601     IYmData20240601Do
	YmData20240602     IYmData20240602Do
	YmData20240603     IYmData20240603Do
	YmData20240604     IYmData20240604Do
	YmData20240605     IYmData20240605Do
	YmData20240606     IYmData20240606Do
	YmData20240607     IYmData20240607Do
	YmData20240608     IYmData20240608Do
	YmData20240609     IYmData20240609Do
	YmData20240610     IYmData20240610Do
	YmData20240611     IYmData20240611Do
	YmData20240612     IYmData20240612Do
	YmData20240613     IYmData20240613Do
	YmData20240614     IYmData20240614Do
	YmData20240615     IYmData20240615Do
	YmData20240616     IYmData20240616Do
	YmData20240617     IYmData20240617Do
	YmData20240618     IYmData20240618Do
	YmDatum            IYmDatumDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		DimensionReference: q.DimensionReference.WithContext(ctx),
		YmData20240101:     q.YmData20240101.WithContext(ctx),
		YmData20240102:     q.YmData20240102.WithContext(ctx),
		YmData20240103:     q.YmData20240103.WithContext(ctx),
		YmData20240104:     q.YmData20240104.WithContext(ctx),
		YmData20240105:     q.YmData20240105.WithContext(ctx),
		YmData20240106:     q.YmData20240106.WithContext(ctx),
		YmData20240107:     q.YmData20240107.WithContext(ctx),
		YmData20240108:     q.YmData20240108.WithContext(ctx),
		YmData20240109:     q.YmData20240109.WithContext(ctx),
		YmData20240110:     q.YmData20240110.WithContext(ctx),
		YmData20240111:     q.YmData20240111.WithContext(ctx),
		YmData20240112:     q.YmData20240112.WithContext(ctx),
		YmData20240113:     q.YmData20240113.WithContext(ctx),
		YmData20240114:     q.YmData20240114.WithContext(ctx),
		YmData20240115:     q.YmData20240115.WithContext(ctx),
		YmData20240116:     q.YmData20240116.WithContext(ctx),
		YmData20240117:     q.YmData20240117.WithContext(ctx),
		YmData20240118:     q.YmData20240118.WithContext(ctx),
		YmData20240119:     q.YmData20240119.WithContext(ctx),
		YmData20240120:     q.YmData20240120.WithContext(ctx),
		YmData20240121:     q.YmData20240121.WithContext(ctx),
		YmData20240122:     q.YmData20240122.WithContext(ctx),
		YmData20240123:     q.YmData20240123.WithContext(ctx),
		YmData20240124:     q.YmData20240124.WithContext(ctx),
		YmData20240125:     q.YmData20240125.WithContext(ctx),
		YmData20240126:     q.YmData20240126.WithContext(ctx),
		YmData20240127:     q.YmData20240127.WithContext(ctx),
		YmData20240128:     q.YmData20240128.WithContext(ctx),
		YmData20240129:     q.YmData20240129.WithContext(ctx),
		YmData20240130:     q.YmData20240130.WithContext(ctx),
		YmData20240131:     q.YmData20240131.WithContext(ctx),
		YmData20240201:     q.YmData20240201.WithContext(ctx),
		YmData20240202:     q.YmData20240202.WithContext(ctx),
		YmData20240203:     q.YmData20240203.WithContext(ctx),
		YmData20240204:     q.YmData20240204.WithContext(ctx),
		YmData20240205:     q.YmData20240205.WithContext(ctx),
		YmData20240206:     q.YmData20240206.WithContext(ctx),
		YmData20240207:     q.YmData20240207.WithContext(ctx),
		YmData20240208:     q.YmData20240208.WithContext(ctx),
		YmData20240209:     q.YmData20240209.WithContext(ctx),
		YmData20240210:     q.YmData20240210.WithContext(ctx),
		YmData20240211:     q.YmData20240211.WithContext(ctx),
		YmData20240212:     q.YmData20240212.WithContext(ctx),
		YmData20240213:     q.YmData20240213.WithContext(ctx),
		YmData20240214:     q.YmData20240214.WithContext(ctx),
		YmData20240215:     q.YmData20240215.WithContext(ctx),
		YmData20240216:     q.YmData20240216.WithContext(ctx),
		YmData20240217:     q.YmData20240217.WithContext(ctx),
		YmData20240218:     q.YmData20240218.WithContext(ctx),
		YmData20240219:     q.YmData20240219.WithContext(ctx),
		YmData20240220:     q.YmData20240220.WithContext(ctx),
		YmData20240221:     q.YmData20240221.WithContext(ctx),
		YmData20240222:     q.YmData20240222.WithContext(ctx),
		YmData20240223:     q.YmData20240223.WithContext(ctx),
		YmData20240224:     q.YmData20240224.WithContext(ctx),
		YmData20240225:     q.YmData20240225.WithContext(ctx),
		YmData20240226:     q.YmData20240226.WithContext(ctx),
		YmData20240227:     q.YmData20240227.WithContext(ctx),
		YmData20240228:     q.YmData20240228.WithContext(ctx),
		YmData20240229:     q.YmData20240229.WithContext(ctx),
		YmData20240301:     q.YmData20240301.WithContext(ctx),
		YmData20240302:     q.YmData20240302.WithContext(ctx),
		YmData20240303:     q.YmData20240303.WithContext(ctx),
		YmData20240304:     q.YmData20240304.WithContext(ctx),
		YmData20240305:     q.YmData20240305.WithContext(ctx),
		YmData20240306:     q.YmData20240306.WithContext(ctx),
		YmData20240307:     q.YmData20240307.WithContext(ctx),
		YmData20240308:     q.YmData20240308.WithContext(ctx),
		YmData20240309:     q.YmData20240309.WithContext(ctx),
		YmData20240310:     q.YmData20240310.WithContext(ctx),
		YmData20240311:     q.YmData20240311.WithContext(ctx),
		YmData20240312:     q.YmData20240312.WithContext(ctx),
		YmData20240313:     q.YmData20240313.WithContext(ctx),
		YmData20240314:     q.YmData20240314.WithContext(ctx),
		YmData20240315:     q.YmData20240315.WithContext(ctx),
		YmData20240316:     q.YmData20240316.WithContext(ctx),
		YmData20240317:     q.YmData20240317.WithContext(ctx),
		YmData20240318:     q.YmData20240318.WithContext(ctx),
		YmData20240319:     q.YmData20240319.WithContext(ctx),
		YmData20240320:     q.YmData20240320.WithContext(ctx),
		YmData20240321:     q.YmData20240321.WithContext(ctx),
		YmData20240322:     q.YmData20240322.WithContext(ctx),
		YmData20240323:     q.YmData20240323.WithContext(ctx),
		YmData20240324:     q.YmData20240324.WithContext(ctx),
		YmData20240325:     q.YmData20240325.WithContext(ctx),
		YmData20240326:     q.YmData20240326.WithContext(ctx),
		YmData20240327:     q.YmData20240327.WithContext(ctx),
		YmData20240328:     q.YmData20240328.WithContext(ctx),
		YmData20240329:     q.YmData20240329.WithContext(ctx),
		YmData20240330:     q.YmData20240330.WithContext(ctx),
		YmData20240331:     q.YmData20240331.WithContext(ctx),
		YmData20240401:     q.YmData20240401.WithContext(ctx),
		YmData20240402:     q.YmData20240402.WithContext(ctx),
		YmData20240403:     q.YmData20240403.WithContext(ctx),
		YmData20240404:     q.YmData20240404.WithContext(ctx),
		YmData20240405:     q.YmData20240405.WithContext(ctx),
		YmData20240406:     q.YmData20240406.WithContext(ctx),
		YmData20240407:     q.YmData20240407.WithContext(ctx),
		YmData20240408:     q.YmData20240408.WithContext(ctx),
		YmData20240409:     q.YmData20240409.WithContext(ctx),
		YmData20240410:     q.YmData20240410.WithContext(ctx),
		YmData20240411:     q.YmData20240411.WithContext(ctx),
		YmData20240412:     q.YmData20240412.WithContext(ctx),
		YmData20240413:     q.YmData20240413.WithContext(ctx),
		YmData20240414:     q.YmData20240414.WithContext(ctx),
		YmData20240415:     q.YmData20240415.WithContext(ctx),
		YmData20240416:     q.YmData20240416.WithContext(ctx),
		YmData20240417:     q.YmData20240417.WithContext(ctx),
		YmData20240418:     q.YmData20240418.WithContext(ctx),
		YmData20240419:     q.YmData20240419.WithContext(ctx),
		YmData20240420:     q.YmData20240420.WithContext(ctx),
		YmData20240421:     q.YmData20240421.WithContext(ctx),
		YmData20240422:     q.YmData20240422.WithContext(ctx),
		YmData20240423:     q.YmData20240423.WithContext(ctx),
		YmData20240424:     q.YmData20240424.WithContext(ctx),
		YmData20240425:     q.YmData20240425.WithContext(ctx),
		YmData20240426:     q.YmData20240426.WithContext(ctx),
		YmData20240427:     q.YmData20240427.WithContext(ctx),
		YmData20240428:     q.YmData20240428.WithContext(ctx),
		YmData20240429:     q.YmData20240429.WithContext(ctx),
		YmData20240430:     q.YmData20240430.WithContext(ctx),
		YmData20240501:     q.YmData20240501.WithContext(ctx),
		YmData20240502:     q.YmData20240502.WithContext(ctx),
		YmData20240503:     q.YmData20240503.WithContext(ctx),
		YmData20240504:     q.YmData20240504.WithContext(ctx),
		YmData20240505:     q.YmData20240505.WithContext(ctx),
		YmData20240506:     q.YmData20240506.WithContext(ctx),
		YmData20240507:     q.YmData20240507.WithContext(ctx),
		YmData20240508:     q.YmData20240508.WithContext(ctx),
		YmData20240509:     q.YmData20240509.WithContext(ctx),
		YmData20240510:     q.YmData20240510.WithContext(ctx),
		YmData20240511:     q.YmData20240511.WithContext(ctx),
		YmData20240512:     q.YmData20240512.WithContext(ctx),
		YmData20240513:     q.YmData20240513.WithContext(ctx),
		YmData20240514:     q.YmData20240514.WithContext(ctx),
		YmData20240515:     q.YmData20240515.WithContext(ctx),
		YmData20240516:     q.YmData20240516.WithContext(ctx),
		YmData20240517:     q.YmData20240517.WithContext(ctx),
		YmData20240518:     q.YmData20240518.WithContext(ctx),
		YmData20240519:     q.YmData20240519.WithContext(ctx),
		YmData20240520:     q.YmData20240520.WithContext(ctx),
		YmData20240521:     q.YmData20240521.WithContext(ctx),
		YmData20240522:     q.YmData20240522.WithContext(ctx),
		YmData20240523:     q.YmData20240523.WithContext(ctx),
		YmData20240524:     q.YmData20240524.WithContext(ctx),
		YmData20240525:     q.YmData20240525.WithContext(ctx),
		YmData20240526:     q.YmData20240526.WithContext(ctx),
		YmData20240527:     q.YmData20240527.WithContext(ctx),
		YmData20240528:     q.YmData20240528.WithContext(ctx),
		YmData20240529:     q.YmData20240529.WithContext(ctx),
		YmData20240530:     q.YmData20240530.WithContext(ctx),
		YmData20240531:     q.YmData20240531.WithContext(ctx),
		YmData20240601:     q.YmData20240601.WithContext(ctx),
		YmData20240602:     q.YmData20240602.WithContext(ctx),
		YmData20240603:     q.YmData20240603.WithContext(ctx),
		YmData20240604:     q.YmData20240604.WithContext(ctx),
		YmData20240605:     q.YmData20240605.WithContext(ctx),
		YmData20240606:     q.YmData20240606.WithContext(ctx),
		YmData20240607:     q.YmData20240607.WithContext(ctx),
		YmData20240608:     q.YmData20240608.WithContext(ctx),
		YmData20240609:     q.YmData20240609.WithContext(ctx),
		YmData20240610:     q.YmData20240610.WithContext(ctx),
		YmData20240611:     q.YmData20240611.WithContext(ctx),
		YmData20240612:     q.YmData20240612.WithContext(ctx),
		YmData20240613:     q.YmData20240613.WithContext(ctx),
		YmData20240614:     q.YmData20240614.WithContext(ctx),
		YmData20240615:     q.YmData20240615.WithContext(ctx),
		YmData20240616:     q.YmData20240616.WithContext(ctx),
		YmData20240617:     q.YmData20240617.WithContext(ctx),
		YmData20240618:     q.YmData20240618.WithContext(ctx),
		YmDatum:            q.YmDatum.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
