// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cmd/gate/main.go/internal/ym/model"
)

func newYmData20240103(db *gorm.DB, opts ...gen.DOOption) ymData20240103 {
	_ymData20240103 := ymData20240103{}

	_ymData20240103.ymData20240103Do.UseDB(db, opts...)
	_ymData20240103.ymData20240103Do.UseModel(&model.YmData20240103{})

	tableName := _ymData20240103.ymData20240103Do.TableName()
	_ymData20240103.ALL = field.NewAsterisk(tableName)
	_ymData20240103.ID = field.NewInt32(tableName, "id")
	_ymData20240103.Timestamp = field.NewTime(tableName, "timestamp")
	_ymData20240103.URLPath = field.NewString(tableName, "url_path")
	_ymData20240103.Browser = field.NewString(tableName, "browser")
	_ymData20240103.Device = field.NewString(tableName, "device")
	_ymData20240103.OperatingSystem = field.NewString(tableName, "operating_system")
	_ymData20240103.Pageviews = field.NewInt32(tableName, "pageviews")
	_ymData20240103.Users = field.NewInt32(tableName, "users")

	_ymData20240103.fillFieldMap()

	return _ymData20240103
}

type ymData20240103 struct {
	ymData20240103Do

	ALL             field.Asterisk
	ID              field.Int32
	Timestamp       field.Time
	URLPath         field.String
	Browser         field.String
	Device          field.String
	OperatingSystem field.String
	Pageviews       field.Int32
	Users           field.Int32

	fieldMap map[string]field.Expr
}

func (y ymData20240103) Table(newTableName string) *ymData20240103 {
	y.ymData20240103Do.UseTable(newTableName)
	return y.updateTableName(newTableName)
}

func (y ymData20240103) As(alias string) *ymData20240103 {
	y.ymData20240103Do.DO = *(y.ymData20240103Do.As(alias).(*gen.DO))
	return y.updateTableName(alias)
}

func (y *ymData20240103) updateTableName(table string) *ymData20240103 {
	y.ALL = field.NewAsterisk(table)
	y.ID = field.NewInt32(table, "id")
	y.Timestamp = field.NewTime(table, "timestamp")
	y.URLPath = field.NewString(table, "url_path")
	y.Browser = field.NewString(table, "browser")
	y.Device = field.NewString(table, "device")
	y.OperatingSystem = field.NewString(table, "operating_system")
	y.Pageviews = field.NewInt32(table, "pageviews")
	y.Users = field.NewInt32(table, "users")

	y.fillFieldMap()

	return y
}

func (y *ymData20240103) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := y.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (y *ymData20240103) fillFieldMap() {
	y.fieldMap = make(map[string]field.Expr, 8)
	y.fieldMap["id"] = y.ID
	y.fieldMap["timestamp"] = y.Timestamp
	y.fieldMap["url_path"] = y.URLPath
	y.fieldMap["browser"] = y.Browser
	y.fieldMap["device"] = y.Device
	y.fieldMap["operating_system"] = y.OperatingSystem
	y.fieldMap["pageviews"] = y.Pageviews
	y.fieldMap["users"] = y.Users
}

func (y ymData20240103) clone(db *gorm.DB) ymData20240103 {
	y.ymData20240103Do.ReplaceConnPool(db.Statement.ConnPool)
	return y
}

func (y ymData20240103) replaceDB(db *gorm.DB) ymData20240103 {
	y.ymData20240103Do.ReplaceDB(db)
	return y
}

type ymData20240103Do struct{ gen.DO }

type IYmData20240103Do interface {
	gen.SubQuery
	Debug() IYmData20240103Do
	WithContext(ctx context.Context) IYmData20240103Do
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IYmData20240103Do
	WriteDB() IYmData20240103Do
	As(alias string) gen.Dao
	Session(config *gorm.Session) IYmData20240103Do
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IYmData20240103Do
	Not(conds ...gen.Condition) IYmData20240103Do
	Or(conds ...gen.Condition) IYmData20240103Do
	Select(conds ...field.Expr) IYmData20240103Do
	Where(conds ...gen.Condition) IYmData20240103Do
	Order(conds ...field.Expr) IYmData20240103Do
	Distinct(cols ...field.Expr) IYmData20240103Do
	Omit(cols ...field.Expr) IYmData20240103Do
	Join(table schema.Tabler, on ...field.Expr) IYmData20240103Do
	LeftJoin(table schema.Tabler, on ...field.Expr) IYmData20240103Do
	RightJoin(table schema.Tabler, on ...field.Expr) IYmData20240103Do
	Group(cols ...field.Expr) IYmData20240103Do
	Having(conds ...gen.Condition) IYmData20240103Do
	Limit(limit int) IYmData20240103Do
	Offset(offset int) IYmData20240103Do
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IYmData20240103Do
	Unscoped() IYmData20240103Do
	Create(values ...*model.YmData20240103) error
	CreateInBatches(values []*model.YmData20240103, batchSize int) error
	Save(values ...*model.YmData20240103) error
	First() (*model.YmData20240103, error)
	Take() (*model.YmData20240103, error)
	Last() (*model.YmData20240103, error)
	Find() ([]*model.YmData20240103, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.YmData20240103, err error)
	FindInBatches(result *[]*model.YmData20240103, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.YmData20240103) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IYmData20240103Do
	Assign(attrs ...field.AssignExpr) IYmData20240103Do
	Joins(fields ...field.RelationField) IYmData20240103Do
	Preload(fields ...field.RelationField) IYmData20240103Do
	FirstOrInit() (*model.YmData20240103, error)
	FirstOrCreate() (*model.YmData20240103, error)
	FindByPage(offset int, limit int) (result []*model.YmData20240103, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IYmData20240103Do
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (y ymData20240103Do) Debug() IYmData20240103Do {
	return y.withDO(y.DO.Debug())
}

func (y ymData20240103Do) WithContext(ctx context.Context) IYmData20240103Do {
	return y.withDO(y.DO.WithContext(ctx))
}

func (y ymData20240103Do) ReadDB() IYmData20240103Do {
	return y.Clauses(dbresolver.Read)
}

func (y ymData20240103Do) WriteDB() IYmData20240103Do {
	return y.Clauses(dbresolver.Write)
}

func (y ymData20240103Do) Session(config *gorm.Session) IYmData20240103Do {
	return y.withDO(y.DO.Session(config))
}

func (y ymData20240103Do) Clauses(conds ...clause.Expression) IYmData20240103Do {
	return y.withDO(y.DO.Clauses(conds...))
}

func (y ymData20240103Do) Returning(value interface{}, columns ...string) IYmData20240103Do {
	return y.withDO(y.DO.Returning(value, columns...))
}

func (y ymData20240103Do) Not(conds ...gen.Condition) IYmData20240103Do {
	return y.withDO(y.DO.Not(conds...))
}

func (y ymData20240103Do) Or(conds ...gen.Condition) IYmData20240103Do {
	return y.withDO(y.DO.Or(conds...))
}

func (y ymData20240103Do) Select(conds ...field.Expr) IYmData20240103Do {
	return y.withDO(y.DO.Select(conds...))
}

func (y ymData20240103Do) Where(conds ...gen.Condition) IYmData20240103Do {
	return y.withDO(y.DO.Where(conds...))
}

func (y ymData20240103Do) Order(conds ...field.Expr) IYmData20240103Do {
	return y.withDO(y.DO.Order(conds...))
}

func (y ymData20240103Do) Distinct(cols ...field.Expr) IYmData20240103Do {
	return y.withDO(y.DO.Distinct(cols...))
}

func (y ymData20240103Do) Omit(cols ...field.Expr) IYmData20240103Do {
	return y.withDO(y.DO.Omit(cols...))
}

func (y ymData20240103Do) Join(table schema.Tabler, on ...field.Expr) IYmData20240103Do {
	return y.withDO(y.DO.Join(table, on...))
}

func (y ymData20240103Do) LeftJoin(table schema.Tabler, on ...field.Expr) IYmData20240103Do {
	return y.withDO(y.DO.LeftJoin(table, on...))
}

func (y ymData20240103Do) RightJoin(table schema.Tabler, on ...field.Expr) IYmData20240103Do {
	return y.withDO(y.DO.RightJoin(table, on...))
}

func (y ymData20240103Do) Group(cols ...field.Expr) IYmData20240103Do {
	return y.withDO(y.DO.Group(cols...))
}

func (y ymData20240103Do) Having(conds ...gen.Condition) IYmData20240103Do {
	return y.withDO(y.DO.Having(conds...))
}

func (y ymData20240103Do) Limit(limit int) IYmData20240103Do {
	return y.withDO(y.DO.Limit(limit))
}

func (y ymData20240103Do) Offset(offset int) IYmData20240103Do {
	return y.withDO(y.DO.Offset(offset))
}

func (y ymData20240103Do) Scopes(funcs ...func(gen.Dao) gen.Dao) IYmData20240103Do {
	return y.withDO(y.DO.Scopes(funcs...))
}

func (y ymData20240103Do) Unscoped() IYmData20240103Do {
	return y.withDO(y.DO.Unscoped())
}

func (y ymData20240103Do) Create(values ...*model.YmData20240103) error {
	if len(values) == 0 {
		return nil
	}
	return y.DO.Create(values)
}

func (y ymData20240103Do) CreateInBatches(values []*model.YmData20240103, batchSize int) error {
	return y.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (y ymData20240103Do) Save(values ...*model.YmData20240103) error {
	if len(values) == 0 {
		return nil
	}
	return y.DO.Save(values)
}

func (y ymData20240103Do) First() (*model.YmData20240103, error) {
	if result, err := y.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.YmData20240103), nil
	}
}

func (y ymData20240103Do) Take() (*model.YmData20240103, error) {
	if result, err := y.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.YmData20240103), nil
	}
}

func (y ymData20240103Do) Last() (*model.YmData20240103, error) {
	if result, err := y.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.YmData20240103), nil
	}
}

func (y ymData20240103Do) Find() ([]*model.YmData20240103, error) {
	result, err := y.DO.Find()
	return result.([]*model.YmData20240103), err
}

func (y ymData20240103Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.YmData20240103, err error) {
	buf := make([]*model.YmData20240103, 0, batchSize)
	err = y.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (y ymData20240103Do) FindInBatches(result *[]*model.YmData20240103, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return y.DO.FindInBatches(result, batchSize, fc)
}

func (y ymData20240103Do) Attrs(attrs ...field.AssignExpr) IYmData20240103Do {
	return y.withDO(y.DO.Attrs(attrs...))
}

func (y ymData20240103Do) Assign(attrs ...field.AssignExpr) IYmData20240103Do {
	return y.withDO(y.DO.Assign(attrs...))
}

func (y ymData20240103Do) Joins(fields ...field.RelationField) IYmData20240103Do {
	for _, _f := range fields {
		y = *y.withDO(y.DO.Joins(_f))
	}
	return &y
}

func (y ymData20240103Do) Preload(fields ...field.RelationField) IYmData20240103Do {
	for _, _f := range fields {
		y = *y.withDO(y.DO.Preload(_f))
	}
	return &y
}

func (y ymData20240103Do) FirstOrInit() (*model.YmData20240103, error) {
	if result, err := y.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.YmData20240103), nil
	}
}

func (y ymData20240103Do) FirstOrCreate() (*model.YmData20240103, error) {
	if result, err := y.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.YmData20240103), nil
	}
}

func (y ymData20240103Do) FindByPage(offset int, limit int) (result []*model.YmData20240103, count int64, err error) {
	result, err = y.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = y.Offset(-1).Limit(-1).Count()
	return
}

func (y ymData20240103Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = y.Count()
	if err != nil {
		return
	}

	err = y.Offset(offset).Limit(limit).Scan(result)
	return
}

func (y ymData20240103Do) Scan(result interface{}) (err error) {
	return y.DO.Scan(result)
}

func (y ymData20240103Do) Delete(models ...*model.YmData20240103) (result gen.ResultInfo, err error) {
	return y.DO.Delete(models)
}

func (y *ymData20240103Do) withDO(do gen.Dao) *ymData20240103Do {
	y.DO = *do.(*gen.DO)
	return y
}
