// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmn = "Smn"

// Smn mapped from table <Smn>
type Smn struct {
	ID              string `gorm:"column:id;primaryKey" json:"id"`
	TopicUrn        string `gorm:"column:topic_urn;not null" json:"topic_urn"`
	SubscriptionUrn string `gorm:"column:subscription_urn;not null" json:"subscription_urn"`
	UserID          string `gorm:"column:userId;not null" json:"userId"`
}

// TableName Smn's table name
func (*Smn) TableName() string {
	return TableNameSmn
}
