// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTwoFactorToken = "TwoFactorToken"

// TwoFactorToken mapped from table <TwoFactorToken>
type TwoFactorToken struct {
	ID      string    `gorm:"column:id;primaryKey" json:"id"`
	Email   string    `gorm:"column:email;not null" json:"email"`
	Token   string    `gorm:"column:token;not null" json:"token"`
	Expires time.Time `gorm:"column:expires;not null" json:"expires"`
}

// TableName TwoFactorToken's table name
func (*TwoFactorToken) TableName() string {
	return TableNameTwoFactorToken
}
