// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUploadedImage = "uploaded_images"

// UploadedImage mapped from table <uploaded_images>
type UploadedImage struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	StorageFilename  string    `gorm:"column:storage_filename;not null" json:"storage_filename"`
	OriginalFilename string    `gorm:"column:original_filename;not null" json:"original_filename"`
	URL              string    `gorm:"column:url;not null" json:"url"`
	FileHash         string    `gorm:"column:file_hash;not null" json:"file_hash"`
	Type             string    `gorm:"column:type;not null" json:"type"`
	Size             string    `gorm:"column:size;not null" json:"size"`
	UploadedAt       time.Time `gorm:"column:uploaded_at;not null;default:CURRENT_TIMESTAMP" json:"uploaded_at"`
	UploadedBy       string    `gorm:"column:uploaded_by;not null" json:"uploaded_by"`
}

// TableName UploadedImage's table name
func (*UploadedImage) TableName() string {
	return TableNameUploadedImage
}
