// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVerificationToken = "VerificationToken"

// VerificationToken mapped from table <VerificationToken>
type VerificationToken struct {
	ID      string    `gorm:"column:id;primaryKey" json:"id"`
	Email   string    `gorm:"column:email;not null" json:"email"`
	Token   string    `gorm:"column:token;not null" json:"token"`
	Expires time.Time `gorm:"column:expires;not null" json:"expires"`
}

// TableName VerificationToken's table name
func (*VerificationToken) TableName() string {
	return TableNameVerificationToken
}
